### ISSUE TITLE
[AVM Question/Feedback]: Split Location Variables for AVD Resources

### ISSUE THREAD

**Issue by PetterHL** [Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane#63]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Issue Proposal: Split Location Variables for AVD Resources

In the current AVM pattern, a single location variable is used for all AVD resources. However, certain AVD components, such as the Workspace and Application Group, necessitate deployment in different regions due to regional support constraints. This constraint is problematic when deploying AVD in regions like Norway East, where AVD Workspaces are not supported. Consequently, I am unable to deploy the Workspace and Application Group in a supported region (e.g., West Europe) while keeping other resources in the desired region.

Current Behavior

- The module requires a single location variable.
- All resources, including Workspace and Application Group, are deployed in the specified location.
- Attempting to deploy unsupported resources in certain regions results in deployment errors.

Desired Behavior

- Ability to specify separate location variables for different resources within the module.
- Enhanced flexibility to deploy resources in regions that support them without modifying the module code

**Comment by jensheerin** [comment]
Hi @PetterHL, Thank you for raising the issue! You raise a good point. I will work on an update. Thank you again!
