### ISSUE TITLE
[AVM Module Issue]: Tags assignment, private connection

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane#67]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Customer feedback - Urgently needed

Tags Assignment in main.privateendpoints.tf:
In the main.privateendpoints.tf file, the tags for the Private Endpoint resource are being passed from each.value.locals.tag. This is causing issues, as the module expects the tags to be provided via the private_endpoints variable instead of referencing the locals block. This discrepancy is leading to unexpected behaviour and deployment errors.
b.	Missing private_connection_resource_ids:
Additionally, within the private_service_connection block of the Private Endpoint resource, the module is referencing private_connection_resource_ids. However, this field is not present in the var.private_endpoints variable definition, which is causing further issues during deployment. 
c.	Here is the URL for main.privateendpoint.tf and variables.tf-
i.	[https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane/blob/v0.1.5/main.privateendpoint.tf](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fterraform-azurerm-avm-ptn-avd-lza-managementplane%2Fblob%2Fv0.1.5%2Fmain.privateendpoint.tf&data=05%7C02%7CPankaj.Meshram%40microsoft.com%7Cc3813589c69e4d212fe908dcec3287c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638644949020557793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=QaHIgJr1tu7wEhmZo%2B3Y1aUS8i59L6zrAP2zBMEh5hE%3D&reserved=0)
ii.	[https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane/blob/v0.1.5/variables.tf](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fterraform-azurerm-avm-ptn-avd-lza-managementplane%2Fblob%2Fv0.1.5%2Fvariables.tf&data=05%7C02%7CPankaj.Meshram%40microsoft.com%7Cc3813589c69e4d212fe908dcec3287c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638644949020574800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=UnAHDwnywNoh2VnrFg%2BObMl%2BKqGHpfB6EL7b0DUdlls%3D&reserved=0)

**Comment by jensheerin** [comment]
fixed with https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane/pull/77
