### ISSUE TITLE
[AVM Module Issue]: Unused and Uncustomizable virtual_desktop_scaling_plan_schedule Parameter

### ISSUE THREAD

**Issue by PetterHL** [Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane#75]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.6

### Issue Summary
The current implementation of the `terraform-azurerm-avm-ptn-avd-lza-managementplane` module does not allow users to pass a custom `virtual_desktop_scaling_plan_schedule` parameter, which limits flexibility in defining specific scaling schedules for Azure Virtual Desktop (AVD). Although variables for `virtual_desktop_scaling_plan_schedule` and related scaling configurations are defined in `variables.tf`, they are not referenced or utilized in `main.tf` or any other part of the module, making these variables effectively unused.

### Expected Behavior
The module should:
1. Reference and use the `virtual_desktop_scaling_plan_schedule` and related variables defined in `variables.tf`.
2. Allow users to pass custom scaling schedules dynamically through input variables without needing to modify the module code.

### Actual Behavior
1. The `virtual_desktop_scaling_plan_schedule` variable (and related scaling variables) is defined in `variables.tf` but is not referenced within `main.tf`, meaning any custom values passed to this variable are ignored.
2. The scaling plan remains hardcoded within the module, preventing users from applying custom scaling schedules.

### Steps to Reproduce
1. Attempt to define a custom `virtual_desktop_scaling_plan_schedule` for AVD scaling by setting the variable.
2. Observe that the variable has no effect, as the parameter is hardcoded in the module’s `main.tf`.

### Suggested Fix
Update `main.tf` to reference the existing `virtual_desktop_scaling_plan_schedule` and related scaling variables from `variables.tf`, allowing users to pass custom schedules with all required parameters (such as `name`, `days_of_week`, `ramp_up_start_time`, etc.).

### Example Implementation for Dynamic Scaling Schedule

```hcl

module "avm_res_desktopvirtualization_scaling_plan" {
  source                                           = "Azure/avm-res-desktopvirtualization-scalingplan/azurerm"
  enable_telemetry                                 = var.enable_telemetry
  version                                          = "0.1.4"
  virtual_desktop_scaling_plan_name                = var.virtual_desktop_scaling_plan_name
  virtual_desktop_scaling_plan_location            = var.virtual_desktop_scaling_plan_location
  virtual_desktop_scaling_plan_resource_group_name = var.resource_group_name
  virtual_desktop_scaling_plan_time_zone           = var.virtual_desktop_scaling_plan_time_zone
  virtual_desktop_scaling_plan_description         = var.virtual_desktop_scaling_plan_description
  virtual_desktop_scaling_plan_tags                = local.tags
  virtual_desktop_scaling_plan_schedule            = var.schedules
  virtual_desktop_scaling_plan_host_pool = toset(
    [
      {
        hostpool_id          = module.avm_res_desktopvirtualization_hostpool.resource.id
        scaling_plan_enabled = true
      }
    ]
  )
 }
```
### Additional Context
This enhancement would improve the module’s flexibility and usability, especially for users who need to set specific scaling schedules for different times of the week or for production environments with customized scaling needs.

**Comment by jensheerin** [comment]
fixed with https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane/pull/77
