### ISSUE TITLE
[AVM Module Issue]: Add Support for Linking to Existing Log Analytics Workspace Across Subscriptions

### ISSUE THREAD

**Issue by PetterHL** [Azure/terraform-azurerm-avm-ptn-avd-lza-managementplane#79]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.7

### Description

**Description:**  
The current implementation of the module creates a new Log Analytics Workspace (LAW) based on the provided parameters (e.g., `log_analytics_workspace_name`, `log_analytics_workspace_location`). However, there is no option to link the Azure Virtual Desktop (AVD) Insights setup to an **existing LAW** in another subscription. This limitation can lead to duplicate LAW instances or prevent integration with an existing cross-subscription LAW.

**Feature Request:**  
Add support to allow referencing an existing Log Analytics Workspace by its **resource ID** instead of creating a new one. This would enable users to:
- Link AVD Insights to an existing LAW across subscriptions.
- Avoid redundant LAW deployments when an organization already has centralized logging configured.

**Proposed Solution:**  
1. Add a new variable, `existing_log_analytics_workspace_id`, which accepts the resource ID of an existing LAW.
2. Modify the `monitor_data_collection_rule_destinations` block to prioritize `existing_log_analytics_workspace_id` if provided.
3. Update the module's logic to skip LAW creation when `existing_log_analytics_workspace_id` is defined.

**Example Configuration:**

```hcl
module "avm_ptn_avd_lza_insights" {
  source                                = "Azure/avm-ptn-avd-lza-insights/azurerm"
  version                               = "0.1.3"
  enable_telemetry                      = var.enable_telemetry
  monitor_data_collection_rule_location = var.monitor_data_collection_rule_location
  monitor_data_collection_rule_name     = var.monitor_data_collection_rule_name

  # Use existing LAW by resource ID
  existing_log_analytics_workspace_id   = "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.OperationalInsights/workspaces/<WORKSPACE_NAME>"

  monitor_data_collection_rule_data_flow = [
    {
      destinations = [var.existing_log_analytics_workspace_id]
      streams      = ["Microsoft-Perf", "Microsoft-Event"]
    }
  ]
  monitor_data_collection_rule_destinations = {
    log_analytics = {
      workspace_resource_id = var.existing_log_analytics_workspace_id
    }
  }
  monitor_data_collection_rule_data_sources = {
    performance_counter = [ ... ]
    windows_event_log   = [ ... ]
  }
}
```

**Benefits:**  
- Simplifies integration with existing monitoring infrastructure.
- Reduces costs associated with duplicate LAW instances.
- Aligns with best practices for cross-subscription resource management.

**Comment by jensheerin** [comment]
Hi @PetterHL, thank you so much for raising the issue. AVD recommends having its own Log analytics Workspace be separate from other Azure resources.
